name: Lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint